apm-server.host: "0.0.0.0:8200"
apm-server.ssl.enabled: true
apm-server.ssl.certificate: "/certs/apm-server/apm-server.crt"
apm-server.ssl.key: "/certs/apm-server/apm-server.key"

output.elasticsearch:
  hosts: ["https://lme-elasticsearch:9200"]
  username: elastic
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl.certificate_authorities: ["/certs/ca/ca.crt"]
