metricbeat.modules:
  - module: system
    metricsets: [cpu, load, memory, network, process, process_summary, socket_summary, filesystem, fsstat, uptime]
    enabled: true
    period: 10s
    processes: ['.*']
    hostfs: /hostfs

output.elasticsearch:
  hosts: ["https://lme-elasticsearch:9200"]
  username: elastic
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl.certificate_authorities: ["/certs/ca/ca.crt"]

setup.kibana:
  host: "https://lme-kibana:5601"
  username: elastic
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl.certificate_authorities: ["/certs/ca/ca.crt"]

setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true
setup.dashboards.retry.interval: 5s

http.enabled: true
